apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  database_url: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpuUEcgNWp5Q1Z4WXI5Yk16QGVwLWJyb2FkLXZpb2xldC1hMTluZm82OC1wb29sZXIuYXAtc291dGhlYXN0LTEuYXdzLm5lb24udGVjaC9uZW9uZGI/c3NsbW9kZT1yZXF1aXJlJmNoYW5uZWxfYmluZGluZz1yZXF1aXJl
  groq_api_key: Z3NrX2dJdVRTZVpwUjVwTXlLcFBvRWp0V0dkeWIzRllWcFpoOGo5YjZmcUhDT3J4eTEwR0pPM0Y=
  secret_key: VmNrM1Q1cUlNVDNhQ3REWGJjWGhDaUNxbk0zZ0hCQVBJVmMxckthdXVTcw==