apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend-chart.fullname" . }}-secrets
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
type: Opaque
data:
  database_url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  nextauth_secret: {{ .Values.secrets.nextauthSecret | b64enc | quote }}